### ISSUE TITLE
Methods not implemented by H5PSymfony

### ISSUE THREAD

**Issue by SundayPlayer** [Emmedy/h5p-bundle#6]
Hi,

It seems that `loadAddons()` and `getLibraryConfig()` are not implemented in H5PSymfony.
So, just after composer require I have this error :
```
Error: Class Emmedy\H5PBundle\Core\H5PSymfony contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (H5PFrameworkInterface::loadAddons, H5PFrameworkInterface::getLibraryConfig)
```

What should i do to correct this issue ?

btw Thank's for this bundle !

**Comment by nieck** [comment]
I think H5P team has changed the interfaces. This version of h5p-bundle works with 1.17.

A quick fix is to change the version in composer.json of h5p-bundle to "1.17" instead of "^1.17". I will fix this later this week.

Thank you for pointing this out.
